### ISSUE TITLE
Dataset sequence length

### ISSUE THREAD

**Issue by Ariande1** [thuml/predrnn-pytorch#15]
Hi
I ran both the MNIST and KTH datasets. But it seems that in the Moving MNIST, there are 2000 test sequences instead of 5000, and in the KTH dataset, it prints that 'there are 8488/5041 sequences'. The number of sequences in the datasets provided seems to be less than that reported in the paper.  Does this matter？

**Comment by wuhaixu2016** [comment]
For the MNIST dataset, you can merge the 'valid'(2000 sequences) and 'test'(3000 sequences) to get 5000 sequences for evaluation. Our results are based on the 'test' set.
For the KTH dataset, I think it is maybe because of the data augmentation. Anyway, you can totally follow this code base. We will give more details in the revision.
