### ISSUE TITLE
Prediction images don't change.

### ISSUE THREAD

**Issue by leelew** [thuml/predrnn-pytorch#30]
Hi, 

I ultilized predRNN and your traininig strategy (i.e., combine reverse schedule sampling and schedule sampling) to give a soil moisture forecasting. We ultilized 7 days soil moisture to predict it on future 7 days. However, I found the prediction images can't capture the evolution of soil moisture during forecasting steps, and give the same pattern of soil moisture on step 8 (see attached figure).

Can you give me some suggestions?
Thanks a lot !

Lu

![fee08917879e8bf9e882655329e5c93](https://user-images.githubusercontent.com/46986798/145949958-096878a8-91f2-41ee-a476-12a05bc550e7.jpg)

**Comment by leelew** [comment]
Actually, I think this is caused by that input X(t) have more information than h(t-1), c(t-1), thus the model tend to forecast a similar image with X(t) (i.e., true image of previous timestep). When we turn train mode to inference mode, the forecasting steps doesn't have corresponding true images from previous timesteps, thus they tend to forecast a similar images as prediction image  of previous timestep. [This is define as difficulty in learning long-term dynamic problem in your paper]. 

Can you give me some suggestion?
Thanks!

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.
(1) I think your case is quite difficult for prediction since the inputs show an accumulation trend (right-top) while the future tends to dissipate.
(2) To emphasis the motion, I think predicting the change between two adjacent frames might be helpful, that is `X_{t}-X_{t-1}`.
(3) Since this problem is quite challenging, maybe you can change the schedule sampling strategy as the input mask start from a high value, such as 0.8. This will not bring too much difficulty for prediction and still force the model to learn the long-term dependecies.

**Comment by leelew** [comment]
Thanks for your insightful suggestion!

**Comment by lsteffenel** [comment]
Hello, I'm facing the same problem (I'm using meteorological images), but I could not understand exactly which parameters to change. 
I'm using the "moving mnist" predrnn_v2_mnist_train.sh as starting point, can you give me some hints on which parameters to change (and which values)?
Thank you!
